reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, only: [:new, :create, :edit, :update, :show, :index, :destroy]
  resources :posts, only: [:new, :create, :show, :edit, :update] do
    resources :comments, only: [:new, :create]
    post 'upvote', to: 'posts#upvote'
    post 'downvote', to: 'posts#downvote'
  end
  resources :comments, only: [:show] do
    post 'upvote', to: 'comments#upvote'
    post 'downvote', to: 'comments#downvote'
  end

  root 'subs#index'

end

reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  author_id  :integer          not null
#  title      :string           not null
#  url        :string           not null
#  content    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, :url, presence: true

  include Upvotable

  belongs_to :author,
   class_name: :User,
   primary_key: :id,
   foreign_key: :author_id

   has_many :post_subs, inverse_of: :sub

   has_many :subs, through: :post_subs

   has_many :comments


end

reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
    @subs = Sub.all
    render :new
  end

  def create
    @post = Post.create(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to subs_url
    else
      @subs = Sub.all
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @subs = Sub.all
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to subs_url
    else
      @subs = Sub.all
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.includes(comments: [:author, :votes], votes: :user).find_by(id: params[:id])
  end

  def upvote
    @post = Post.find(params[:post_id])
    @post.upvote(current_user)
    redirect_to subs_url
  end

  def downvote
    @post = Post.find(params[:post_id])
    @post.downvote(current_user)
    redirect_to subs_url
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

reddit_clone/app/views/posts/_comment.html.erb
<ol>
  <% @post.comments.each do |comment| %>
    <% if comment.parent_comment_id == parent_id %>
      <li><a href="<%= comment_url(comment) %>"> (<%= comment.vote_count %>) <%= comment.content %></a> by <strong><%= comment.author.username %></strong></li>
      <%= render 'comment', parent_id: comment.id %>
    <% end %>
  <% end %>
</ol>

reddit_clone/app/views/posts/edit.html.erb
<nav class='sub-nav'>
  <h1> Edit Post </h1>
</nav>

<% flash[:errors].try(:each) do |error| %>
 <%= error %>
<% end %>

<form class="form" action="<%= post_url(@post) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="PATCH">
  <label for="title">Title*: </label>
  <input id="title" type="text" name="post[title]" value="<%= @post.title %>">
  <label for="url">URL*: </label>
  <input id="url" type="text" name="post[url]" value="<%= @post.title %>">
  <label for="content">Content: </label>
  <textarea id="content" rows='10' name="post[content]"><%= @post.content %></textarea>
  <label>Subs</label>
  <input type="hidden" name="post[sub_ids][]" value="">
  <div class="checksubs">

    <% @subs.each do |each_sub| %>
    <label><%= each_sub.title %>:
    <input type="checkbox" name="post[sub_ids][]" value="<%= each_sub.id %>" <%= "checked" if @post.sub_ids.include?(each_sub.id) %> ></label>
    <% end %>
  </div>
  <input type="submit" class='button submit' value="Edit Post">
</form>

reddit_clone/app/views/posts/new.html.erb
<nav class='sub-nav'>
  <h1> New Post </h1>
</nav>

<% flash[:errors].try(:each) do |error| %>
 <%= error %>
<% end %>

<form class="form" action="<%= posts_url %>" method="post">
  <%= auth_token %>
  <label for="title">Title*: </label>
  <input id="title" type="text" name="post[title]" value="<%= @post.title %>">
  <label for="url">URL*: </label>
  <input id="url" type="text" name="post[url]" value="<%= @post.title %>">
  <label for="content">Content: </label>
  <textarea id="content" rows='10' name="post[content]"><%= @post.content %></textarea>
  <label>Subs</label>
  <input type="hidden" name="post[sub_ids][]" value="">
  <div class="checksubs">
    <% @subs.each do |each_sub| %>
    <label><%= each_sub.title %>:
    <input type="checkbox" name="post[sub_ids][]" value="<%= each_sub.id %>"></label>
    <% end %>
  </div>
  <input type="submit" class='button submit' value="Create Post">
</form>

reddit_clone/app/views/posts/show.html.erb
<nav class='sub-nav'>
  <h1><a href="<%= @post.url %>"><%= @post.title %></a></h1>
  <ul>
    <li><%= link_to 'Edit', edit_post_url, class: 'button-outline' %></li>
    <li><%= link_to 'Back to Posts', sub_url, class: 'button' %></li>
  </ul>
</nav>
<div class="content-box">
  <p>content:</p>
  <p class='content'><%= @post.content %></p>
</div>

<div class="post-subs">
  <h2><a href="<%= subs_url %>">subs:</a></h2>
  <ul>
    <% @post.subs.each do |each_sub| %>
    <li><%= each_sub.title %></li>
    <% end %>
  </ul>
</div>

<h2>Comments: </h2>
<br>
<div class="button-group">
  <%= link_to 'New Comment', new_post_comment_url(@post), class: 'button-outline' %>
  <%= button_to 'Upvote', post_upvote_url(@post), method: :post, class: 'upvote' %>
  <%= button_to 'Downvote',  post_downvote_url(@post), method: :post, class: 'downvote' %>
</div>
<br><br><br>
<div class="post-comments">
  <%= render 'comment', parent_id: nil %>
</div>

<h2>History of votes</h2>
<ol>
  <% @post.votes.each do |vote| %>
  <li><%= vote.upvote_type %>voted by <%= vote.user.username %></li>
  <% end %>
</ol>