reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, only: [:new, :create, :edit, :update, :show, :index, :destroy]
  resources :posts, only: [:new, :create, :show, :edit, :update] do
    resources :comments, only: [:new, :create]
    post 'upvote', to: 'posts#upvote'
    post 'downvote', to: 'posts#downvote'
  end
  resources :comments, only: [:show] do
    post 'upvote', to: 'comments#upvote'
    post 'downvote', to: 'comments#downvote'
  end

  root 'subs#index'

end

reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  moderator_id :integer          not null
#  title        :string           not null
#  description  :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, presence: true

  belongs_to :moderator,
   class_name: :User,
   primary_key: :id,
   foreign_key: :moderator_id

   has_many :post_subs, inverse_of: :post
   has_many :posts, through: :post_subs

end

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def update
    @sub = Sub.find_by(id: params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def index
    @subs = Sub.all.order(:title)
  end

  def show
    @sub = Sub.find(params[:id])
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_clone/app/views/subs/edit.html.erb
<nav class='sub-nav'>
  <h1> Edit Sub </h1>
</nav>

<% flash[:errors].try(:each) do |error| %>
 <%= error %>
<% end %>

<form class="form" action="<%= sub_url %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <%= auth_token %>
  <label for="title">Title*: </label>
  <input id="title" type="text" name="sub[title]" value="<%= @sub.title %>">
  <label for="description">Description: </label>
  <textarea id="description" rows='10' name="sub[description]"><%= @sub.description %></textarea>
  <input type="submit" class='button submit' value="Save Changes">
</form>

reddit_clone/app/views/subs/index.html.erb
<nav class='sub-nav'>
  <h1> Subs </h1>
  <ul>
    <li><%= link_to 'New Sub', new_sub_url, class: 'button' %></li>
  </ul>
</nav>

<ul>
<% @subs.each do |sub| %>
  <li><a href="<%= sub_url(sub) %>" class="sub-title"><%= sub.title %>: <span class='description'><%= sub.description %></span></a></li>
<% end %>
</ul>

reddit_clone/app/views/subs/new.html.erb
<nav class='sub-nav'>
  <h1> New Sub </h1>
</nav>

<% flash[:errors].try(:each) do |error| %>
 <%= error %>
<% end %>

<form class="form" action="<%= subs_url %>" method="post">
  <%= auth_token %>
  <label for="title">Title*: </label>
  <input id="title" type="text" name="sub[title]" value="<%= @sub.title %>">
  <label for="description">Description: </label>
  <textarea id="description" rows='10' name="sub[description]"><%= @sub.description %></textarea>
  <input type="submit" class='button submit' value="Create Sub">
</form>

reddit_clone/app/views/subs/show.html.erb
<nav class='sub-nav'>
  <h1> <%= @sub.title %> </h1>
  <ul>
    <li><%= link_to 'Edit', edit_sub_url, class: 'button-outline' %></li>
    <li><%= link_to 'Back to Subs', subs_url, class: 'button' %></li>
  </ul>
</nav>

<div class="description-box">
  <h2>Description: </h2>
  <p><%= @sub.description %> </p>
</div>

<ul>
<% @sub.posts.each do |post| %>
<li><a href="<%= post_url(post) %>" class='sub-title'>(<%= post.vote_count %>) <%= post.title %></a></li>
<% end %>
</ul>

<br>


<%= link_to 'New Post', new_post_url, class: 'button' %>