reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, only: [:new, :create, :edit, :update, :show, :index, :destroy]
  resources :posts, only: [:new, :create, :show, :edit, :update] do
    resources :comments, only: [:new, :create]
    post 'upvote', to: 'posts#upvote'
    post 'downvote', to: 'posts#downvote'
  end
  resources :comments, only: [:show] do
    post 'upvote', to: 'comments#upvote'
    post 'downvote', to: 'comments#downvote'
  end

  root 'subs#index'

end

reddit_clone/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :integer          not null, primary key
#  content           :string           not null
#  author_id         :integer
#  post_id           :integer
#  parent_comment_id :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Comment < ApplicationRecord

  validates :content, presence: true

  include Upvotable

  belongs_to :post

  belongs_to :author,
   class_name: :User,
   primary_key: :id,
   foreign_key: :author_id

  belongs_to :parent_comment, optional: true

  has_many :child_comments,
   class_name: :Comment,
   primary_key: :id,
   foreign_key: :parent_comment_id

end

reddit_clone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    render :new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.post_id = params[:post_id]
    if params[:parent_comment_id]
      @comment.parent_comment_id = params[:parent_comment_id]
    end
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = Comment.includes(votes: :user).find_by(id: params[:id])
    @reply_comment = Comment.new
  end

  def upvote
    @comment = Comment.find_by(id: params[:comment_id])
    @comment.upvote(current_user)
    redirect_to post_url(@comment.post)
  end

  def downvote
    @comment = Comment.find_by(id: params[:comment_id])
    @comment.downvote(current_user)
    redirect_to post_url(@comment.post)
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

reddit_clone/app/helpers/comments_helper.rb
module CommentsHelper
end

reddit_clone/app/views/comments/new.html.erb
<nav class='sub-nav'>
  <h1> New Comment </h1>
</nav>

<% flash[:errors].try(:each) do |error| %>
 <%= error %>
<% end %>

<form class="form" action="<%= post_comments_url %>" method="post">
  <%= auth_token %>
  <label for="content">Content: </label>
  <textarea id="content" rows='10' name="comment[content]"><%= @comment.content %></textarea>
  <input type="submit" class='button submit' value="Post Comment">
</form>

reddit_clone/app/views/comments/show.html.erb
<nav class='sub-nav'>
  <h1>Comment </h1>
</nav>

<%= @comment.content %>

<div class="button-group">
<%= button_to 'Upvote', comment_upvote_url(@comment), method: :post, class: 'upvote' %>
<%= button_to 'Downvote',  comment_downvote_url(@comment), method: :post, class: 'downvote' %>
</div>

<form class="form reply-form" action="<%= post_comments_url(@comment.post) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="parent_comment_id" value="<%= @comment.id %>">
  <textarea id="content" rows='10' name="comment[content]"><%= @reply_comment.content %></textarea>
  <input type="submit" class='button submit' value="Post Reply">
</form>

<h2>History of votes</h2>
<br>
<ol>
  <% @comment.votes.each do |vote| %>
  <li><%= vote.upvote_type %>voted by <%= vote.user.username %></li>
  <% end %>
</ol>